### PR TITLE
Add support for mouseEnter and mouseLeave events on a row

### PR DESCRIPTION
**Pull request by Techn1x**
Was this PR https://github.com/offirgolan/ember-light-table/pull/528

Rebased

### CODE REVIEW

**Comment by Techn1x** [comment]
@offirgolan @buschtoens This seems as simple and straightforward and complete as a PR can get - is there anything blocking this from being merged? Thanks

**Comment by rwwagner90** [comment]
👋 We just merged the 3-x branch into master. Can you please rebase your PR?

**Comment by Techn1x** [comment]
Congrats! :tada: 

3 years since my original PR opened :joy: I don't use this addon at my current job, but I will of course do my best to rebase it and get tests passing

**Comment by Techn1x** [comment]
All updated @rwwagner90 - commits are a bit of a mess, might be best to squash merge it. Thanks for putting time into this addon

**Comment by Techn1x** [comment]
CI failed for ember-release scenario, looks like an issue to do with ember font awesome?
```
Template Compiler Error (broccoli-persistent-filter:TemplateCompiler) in ember-font-awesome/components/fa-icon/template.hbs
loc$$1.sliceStartChars is not a function
```

**Comment by Techn1x** [comment]
I give up - I feel like I did everything I could to get this fairly simple PR across the line.

That CI issue is clearly an unrelated problem to my work
https://github.com/emberjs/ember.js/issues/19432

No hate or disrespect to anyone - we're all busy people. I opened the original PR in 2017, I haven't used this addon for years, built my own table components from scratch with modern Ember patterns, and I don't really care for shepherding this anymore.

**Pull request closed without merging**
