### PR TITLE
Merge post 2.0.0-beta.5 branches

### PR DESCRIPTION
**Pull request by maxwondercorn**
The PR merges branches `origin/fw/update-dummy-app` and `3.0.0-beta.0` by @Gorzas  and @fran-worley.  This is work after v2.0.0-beta.5 not merged into master.

I will continue updating the addon after the PR is merged.

edited: Merge only, no release...

### CODE REVIEW

**Comment by rwwagner90** [comment]
@maxwondercorn could we also add a GitHub actions setup to run tests please? I would like to make sure tests are passing before merging.

**Comment by maxwondercorn** [comment]
Yes, I will set that up

**Comment by rwwagner90** [comment]
@maxwondercorn looks like we have a lot of lint failures. Can you please disable those rules or address the issues?

**Comment by maxwondercorn** [comment]
The rules were prematurely removed in one of the merged branches. Will fix or add them back. 

Also working on Ember 3.20 failing tests

**Comment by maxwondercorn** [comment]
@rwwagner90 

Tests are passing in CI. 🎉    Still a lot of work to do but this is a good starting point to continue from

I need to figure out testing differences between local and GitHub actions.  Using `ember-try` locally the `embroider` tests pass but not in CI.  Locally 3.20 source tests fail but pass in CI 🤷

**Pull request merged**
